In [1]:
import requests 
from datetime import datetime, timezone
import pandas as pd

def get_metar_data(id="EGLC"):
    response = requests.get(
        'https://aviationweather.gov/api/data/metar',
        params={'ids': id, 'format': 'json'}
    )
    data = response.json()
    return data

"""
Found the ID at: https://aviationweather.gov/
"""

## london ID
id = "EGLC"
response = requests.get(
    'https://aviationweather.gov/api/data/metar',
    params={'ids': id, 'format': 'json'}
)

data = response.json()


print(data)

[{'icaoId': 'EGLC', 'receiptTime': '2026-02-26T11:24:16.667Z', 'obsTime': 1772104800, 'reportTime': '2026-02-26T11:20:00.000Z', 'temp': 12, 'dewp': 8, 'wdir': 220, 'wspd': 13, 'visib': '6+', 'altim': 1017, 'qcField': 2, 'metarType': 'METAR', 'rawOb': 'METAR EGLC 261120Z AUTO 22013KT 180V260 9999 BKN017 OVC023 12/08 Q1017', 'lat': 51.505, 'lon': 0.055, 'elev': 10, 'name': 'London City Arpt, EN, GB', 'cover': 'OVC', 'clouds': [{'cover': 'BKN', 'base': 1700}, {'cover': 'OVC', 'base': 2300}], 'fltCat': 'MVFR'}]

In [2]:
df = pd.DataFrame().from_dict(data)

## convert the time of the observation to dateitme
df['obsTime'] = df['obsTime'].apply(lambda x: datetime.fromtimestamp(int(x),
                                                                        tz = timezone.utc))

## filter only the selected rows
df = df[['icaoId','obsTime','reportTime','temp','dewp','wdir','wspd','qcField']]

In [3]:
df.head()

,icaoId,obsTime,reportTime,temp,dewp,wdir,wspd,qcField
0,EGLC,2026-02-26 11:20:00+00:00,2026-02-26T11:20:00.000Z,12,8,220,13,2

In [27]:
df.head()

  icaoId                   obsTime  temp  dewp  wdir  wspd  qcField
0   EGLC 2026-02-16 16:50:00+00:00     8     3   280    16        2

In [14]:
pd.to_datetime(df['obsTime'], utc=True)

0   1970-01-01 00:00:01.771260600+00:00
Name: obsTime, dtype: datetime64[ns, UTC]

In [17]:
datetime.now().strftime("%H:%M:%S")

'13:20:45'

In [6]:
import numpy as np 
def get_metar_data(id="EGLC"):
    response = requests.get(
        'https://aviationweather.gov/api/data/metar',
        params={'ids': id, 'format': 'json'}
    )
    data = response.json()
    return data

def make_df_metar(data):
    df = pd.DataFrame().from_dict(data)

    ## convert the time of the observation to dateitme
    df['obsTime'] = df['obsTime'].apply(lambda x: datetime.fromtimestamp(int(x),
                                                                            tz = timezone.utc))

    ## filter only the selected rows
    df = df[['icaoId','obsTime','reportTime','temp','dewp','wdir','wspd','qcField']]

    return df

In [10]:
import time
from datetime import datetime, timezone
import numpy as np
reference_minutute = np.array([20,50])

## GET TIME NOW 
actual = datetime.now()
print(f"TIME NOW:{actual.strftime('%H:%M:%S')}")
actual_minute =actual.minute
correct_min_evaluate = reference_minutute[np.argmin(np.abs(reference_minutute - actual_minute))]

## FIRST API CALL 
data = get_metar_data()
obstime = datetime.fromtimestamp(int(data[0].get('obsTime')),tz = timezone.utc)

while obstime.minute != correct_min_evaluate:
    print(f"Waiting for the right minute: {correct_min_evaluate} - actual minute: {obstime.minute}")
    data = get_metar_data()
    obstime = datetime.fromtimestamp(int(data[0].get('obsTime')),tz = timezone.utc)
    time.sleep(15)

## pass to a df 
df = make_df_metar(data)
df.head()

TIME NOW:13:52:12
Waiting for the right minute: 50 - actual minute: 20

Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20
Waiting for the right minute: 50 - actual minute: 20

,icaoId,obsTime,reportTime,temp,dewp,wdir,wspd,qcField
0,EGLC,2026-02-26 12:50:00+00:00,2026-02-26T13:00:00.000Z,13,8,220,15,2

In [32]:
data = get_metar_data()

In [33]:
data.get('ObsTime')

AttributeError: 'list' object has no attribute 'get'

In [40]:

obstime = datetime.fromtimestamp(int(data[0].get('obsTime')),tz = timezone.utc)
obstime.minute

50

In [ ]:
data[0]data[0]

{'icaoId': 'EGLC',
 'receiptTime': '2026-02-25T11:54:29.484Z',
 'obsTime': 1772020200,
 'reportTime': '2026-02-25T12:00:00.000Z',
 'temp': 16,
 'dewp': 11,
 'wdir': 220,
 'wspd': 6,
 'visib': '6+',
 'altim': 1015,
 'qcField': 2,
 'metarType': 'METAR',
 'rawOb': 'METAR EGLC 251150Z AUTO 22006KT 190V260 9999 NCD 16/11 Q1015',
 'lat': 51.505,
 'lon': 0.055,
 'elev': 10,
 'name': 'London City Arpt, EN, GB',
 'cover': 'CLR',
 'clouds': [],
 'fltCat': 'VFR'}